import Head from 'next/head'
import Image from 'next/image'
import Header from '../../components/Header'
import styles from './styles.module.css'

export default function SetorFeminina() {
  return (
    <>
      <Head>
        <title>Feminina</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header />
      <main className={styles.main}>
       <h1>Moda Feminina</h1>
      </main>
      
    </>
  )
}